
const ACTION_PREFIX = '@RCT';
const APP_STATE_CHANGED = `${ACTION_PREFIX}/APP_STATE_CHANGED`;
const NET_INFO_CHANGED = `${ACTION_PREFIX}/NET_INFO_CHANGED`;

export {
  APP_STATE_CHANGED,
  NET_INFO_CHANGED,
};
